INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (1, N'Nino', N'tutorial', 1, N'Au,au. Acho que você é meu novo mestre, pode me chamar de Nino !', 0)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (2, N'Nino', N'tutorial', 2, N'Serei seu guia nesse jogo criado pelo meu primeiro mestre.', 1)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (3, N'Nino', N'tutorial', 3, N'O jogo funciona da seguinte forma, au, au.', 2)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (4, N'Nino', N'tutorial', 4, N'Tá vendo aqueles botões ali em baixo?', 3)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (5, N'Nino', N'tutorial', 5, N'Au, au, eu os apelidei de botões das decisões.', 4)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (6, N'Nino', N'tutorial', 6, N'Você sempre terá quatro opções de escolha para suas decisões que sempre estaram neles.', 5)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (7, N'Nino', N'tutorial', 7, N'Durante a jogatina você se encontrará em diversas situações de dialogo e ações.', 6)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (8, N'Nino', N'tutorial', 8, N'Tá vendo aqueles dois ali?', 7)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (9, N'Nino', N'tutorial', 9, N'Vou usá-los como exemplo para explicar  a você como o jogo funciona. ', 8)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (10, N'NPC_Samara', N'tutorial', 1, N'Oi, seu amigo disse que você queria falar comigo.', 9)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (11, N'Jogador', N'tutorial', 1, N'Droga, aquele desgraçado do Luan, sabia que não era pra ter falado com ele.', 10)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (12, N'Nino', N'tutorial', 10, N'Escolha uma das opções para responder a pergunta da personagem, au, au.', 11)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (13, N'Nino', N'tutorial', 11, N'Caso você não selecione uma das opções, será escolhida aleatoriamente uma alternativa, au, au.', 12)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (14, N'Jogador', N'tutorial', 2, NULL, 13)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (15, N'NPC_Samara', N'tutorial', 2, NULL, 14)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (16, N'Nino', N'tutorial', 12, NULL, 15)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (17, N'Nino', N'tutorial', 13, NULL, 16)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (18, N'Nino', N'tutorial', 14, N'As decisões são dividas em decisão ruim, decisão neutra e decisão boa.', 17)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (19, N'Nino', N'tutorial', 17, N'Você deve ter percebido aquele icone de cachorro no lado inferior esquerdo.', 18)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (20, N'Nino', N'tutorial', 15, N'Ao longo do jogo você pode se deparar com uma decisão nexus.', 19)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (21, N'Nino', N'tutorial', 16, N'Decisões nexus são aquelas em que mudaram o rumo da sua história e terão um tempo para serem respondidas.', 20)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (22, N'Nino', N'tutorial', 18, N'Aqueles icones representam a qualidade de sua decisão.', 21)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (23, N'Nino', N'tutorial', 19, N'Por hoje é tudo,  te vejo por ai, au, au!', 22)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (24, N'Nino', N'tutorial', 0, N'0', 23)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (25, N'Jogador', N'1', 1, N'zzzzz...', 0)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (26, N'Celular', N'1', 1, N'Trrrim-trrrimmmmmmmm', 1)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (27, N'Jogador', N'1', 2, N'Alou?', 2)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (28, N'Celular', N'1', 2, N'Fala seu bosta, é o Autista.', 3)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (29, N'Jogador', N'1', 3, N'Fala mano, o que você quer?', 4)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (30, N'Celular', N'1', 3, N'Entra no Howitzer ai, bora jogar', 5)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (31, N'Jogador', N'1', 4, N'Cara, são 7h da manhã, e você tá me acordando pra jogar Howitzer?', 6)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (32, N'Celular', N'1', 4, N'Sim', 7)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (33, N'Jogador', N'1', 5, N'Tá, tá bom, vou entrar. Espera só eu ligar o pc.', 8)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (34, N'Jogador', N'1', NULL, NULL, 9)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (35, N'Jogador', N'1', 6, N'Cara, o que essa bolinha tá fazendo aqui?', 10)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (36, N'Jogador', N'1', NULL, NULL, 11)
INSERT INTO [dbo].[Dialogo] ([ID_Falas], [Personagem], [Capitulos], [Num_Fala], [Falas], [Quadro]) VALUES (37, N'Jogador', N'1', NULL, NULL, 12)
